### ISSUE TITLE
cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler'

### ISSUE THREAD

**Issue by lematmat** [Novetta/adaptnlp#114]
**Describe the bug**
Your demo Colab Notebook "Custom Fine-Tuning and Training with Transformer Models" doesn't work and generates the following error:
![image](https://user-images.githubusercontent.com/19993147/110918116-09667f80-831b-11eb-81aa-9f26a856e89f.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by muellerzr** [comment]
In the meantime before I'm able to look at this, install pytorch 1.7.1 before installing adapt, IE:

```python
pip3 install torch==1.7.1
pip3 install adaptnlp
```

**Comment by lematmat** [comment]
Thank you very much.

**Comment by muellerzr** [comment]
@lematmat can you please add a link to that notebook? I don't find it here in the repository. Thanks!

**Comment by ibombonato** [comment]
I guess it is this notebook listed at https://novetta.github.io/adaptnlp/

https://colab.research.google.com/github/Novetta/adaptnlp/blob/master/tutorials/Finetuning%20and%20Training%20(Advanced)/Fine-tuning%20Language%20Model.ipynb

![image](https://user-images.githubusercontent.com/1737342/113916757-be734700-97b6-11eb-96a2-c5e386bf1336.png)

For now it appears that all of the Colab notebooks are not working because of broken references/versions.

**Comment by muellerzr** [comment]
This will soon be fixed once we convert over to nbdev :) However I also didn't see that import anywhere in there 

If it does, replace that with:
```python
try:
    from torch.optim.lr_scheduler import SAVE_STATE_WARNING
except ImportError:
    SAVE_STATE_WARNING = ""
```
