### ISSUE TITLE
Sequence classification using REST API fails with models except en-sentiment

### ISSUE THREAD

**Issue by VogtAI** [Novetta/adaptnlp#78]
Sequence classification over REST API using any model except for en-sentiment fails with:

`
  File "/usr/local/lib/python3.6/dist-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.6/dist-packages/fastapi/routing.py", line 197, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/usr/local/lib/python3.6/dist-packages/fastapi/routing.py", line 147, in run_endpoint_function
    return await dependant.call(**values)
  File "./app/main.py", line 87, in sequence_classifier
    text=text, mini_batch_size=1, model_name_or_path=_SEQUENCE_CLASSIFICATION_MODEL
  File "/adaptnlp/adaptnlp/sequence_classification.py", line 285, in tag_text
    return classifier.predict(text=text, mini_batch_size=mini_batch_size, **kwargs,)
  File "/adaptnlp/adaptnlp/sequence_classification.py", line 140, in predict
    text_sent.add_label(label)
TypeError: add_label() missing 1 required positional argument: 'value'
`

Reproducable with:
`
docker run -itp 5000:5000 -e TOKEN_TAGGING_MODE='ner' \
                          -e TOKEN_TAGGING_MODEL='ner-ontonotes-fast' \
                          -e SEQUENCE_CLASSIFICATION_MODEL='nlptown/bert-base-multilingual-uncased-sentiment' \
                          achangnovetta/adaptnlp-rest:latest \
                          bash
`

**Comment by aychang95** [comment]
This is due to a temporary incompatibility with the latest Flair release. Thank you for bringing this to my attention! 

We will have a release later this week that will address this issue and update the dependencies. We will also integrate the transformer's models into the rest api.

**Comment by aychang95** [comment]
Thanks again for bringing this up and waiting for the updates on this!

Please checkout the updated docs and instructions on the FastAPI endpoints for the the NLP tasks here: https://novetta.github.io/adaptnlp/rest.html

I have made a major change in how the endpoints are deployed by creating a independent service deployments for each NLP task (since the number of tasks and capabilities adaptnlp provides is growing). Hopefully this is not too much of an inconvenience if you preferred the former set up.

If you'd like to deploy endpoints for a sequence classifier you could just run:
```docker run -itp 5000:5000 -e SEQUENCE_CLASSIFICATION_MODEL=nlptown/bert-base-multilingual-uncased-sentiment achangnovetta/sequence-classification:latest bash```

The endpoints for the other tasks like token tagging and question answering can be deployed in a similar fashion. Please let me know if you run into any other issues since these features are pretty fresh.

**Comment by aychang95** [comment]
Closing issue unless noted otherwise
