### ISSUE TITLE
Significant slowdown in EasyTokenTagger release 0.2.0

### ISSUE THREAD

**Issue by mkongsiri-Novetta** [Novetta/adaptnlp#83]
I'm experiencing a slowdown in NER performance using EasyTokenTagger and 'ner-ontonotes' after updating to release 0.20. Has there been any underlying changes to how the tagger object works?

Specifically, I am dealing with a very large chunk of text. Prior to this release, the NER tagging took around 15 seconds for this particular text. Now, it's taking 15+ minutes the first time but subsequent calls on that text are very quick. Is there some sort of caching or indexing that's being done now? I'd imagine this could create a lot of overhead for large chunks of text.

**Comment by aychang95** [comment]
Thanks for bringing this up!

The underlying changes in the tagger object should not have affected compute time to the extent of 15s->15+ minutes.

How large is your example text?
Are you using a GPU for this? If so could you check that `import torch; torch.cuda.is_available()` is returning True?
  - Adaptnlp will automatically install the latest pytorch stable relase version above 1.4.0 so it may have installed an incompatible version and may need downgrading.

I've tried to replicate the slow down with the "ner-ontonotes" model and have gotten the benchmarks below in colab with a P100 GPU with torch 1.6.0:
- ~1,000 token text -> 2.2 seconds
- ~10,000 token text -> 22.4 seconds

Note: When you first instantiate `EasyTokenTagger` and call `tag_text(...)` with a specific model, it will dynamically load the model before running inference which will take up some time. All subsequent `tag_text()` with that particular model will be much faster since it will only run a forward pass on the loaded model.

Hopefully this helps, but there could be something I may be missing so please let me know if this issue persists.

**Comment by mkongsiri-Novetta** [comment]
Thank you for the update.

The magnitude of the text I am running on is in the order of 1,000's. Your note about the model loading taking up some time with subsequent calls being fast is spot on (I should have been more clear in the original post) and I am receiving similar performance benchmarks on the second and subsequent calls to the tagger so I'm fairly confident that GPU is being utilized correctly.

My main issue is that the model loading is taking much longer than it used on that very first invocation of the tagger. I guess what I am trying to figure out is if there were any changes to the model loading procedure in 0.2.0 or if something about my setup changed when I wrapped my application in Docker (or possibly a combination of both?).

**Comment by aychang95** [comment]
@mkongsiri-Novetta just pinging to see if this is still an issue?

**Comment by mkongsiri-Novetta** [comment]
@aychang95 I don't believe this is an issue anymore, it was just the initial loading of the model that created a bottleneck.
