### ISSUE TITLE
EasySequenceClassifier tag_text function returns None for FlairSequenceClassifier model

### ISSUE THREAD

**Issue by DinaraN** [Novetta/adaptnlp#99]
Hi!
I tried to follow the tutorial for training custom sequence classifier: https://novetta.github.io/adaptnlp/tutorial/training-sequence-classification.html
The last step returns empty sentences while expected labels:
`sentences = classifier.tag_text(example_text, model_name_or_path=OUTPUT_DIR)`

To Reproduce the behavior:
```
from adaptnlp import EasySequenceClassifier
from flair.data import Sentence

OUTPUT_DIR = "…/best-model.pt"    # my custom model
classifier = EasySequenceClassifier()

ex_text = "This is a good text example"
example_text=[Sentence(ex_text)]

sentences = classifier.tag_text(text=example_text, model_name_or_path=OUTPUT_DIR, mini_batch_size=1)
print("Label output:\n")
print(sentences)
```
Returns
```
2020-12-28 17:44:31,111 loading file .../best-model.pt
Label output:

None
```
Surprisingly labels got added to example_text
`print(example_text)`
Returns
`[Sentence: " This is a good text example "   [− Tokens: 17  − Sentence-Labels: {'label': [0 (0.8812)]}]]`

Proposed explanation/ contribution:
I think I know the reason for unexpected behavior and will be happy to help.
classifier.tag_text creates FlairSequenceClassifier classifier.
FlairSequenceClassifier initiates flair.models.TextClassifier classifier and uses TextClassifier predict method within its own predict method. 
But flair.models.TextClassifier predict method returns None because the labels are directly added to the sentences. I can re-write FlairSequenceClassifier predict method to return Sentences with labels instead of None.

**Comment by aychang95** [comment]
Hi @DinaraN, sorry about the wait and I hope you enjoyed the holidays!

I agree with your explanation and thoughts, the labels are being correctly added as label attributes to the `Sentence` object you are running inference on. However like you said, it seems we're not returning the sentence or label outputs which is on us. Feel free to add a PR if you've already addressed the issue, otherwise we will probably have it addressed in our next batch of updates and release.

Thank you for the issue as well! Let me know if you have any other questions regarding this thread

**Comment by muellerzr** [comment]
@aychang95 looks like this can be closed since a PR was merged?

**Comment by aychang95** [comment]
Yep, closing since PR addresses this. Thanks for the heads up!
